ALTER TABLE urls
ALTER COLUMN status DROP DEFAULT;

ALTER TABLE urls
ALTER COLUMN status TYPE VARCHAR(128);

ALTER TABLE urls
ADD CHECK (status IN ('ACTIVE', 'INACTIVE'));

ALTER TABLE urls
ALTER COLUMN status SET DEFAULT 'ACTIVE';

DROP TYPE url_status;